#!/bin/bash
#
# Copies a html file without its sorting prefix
#
#  Copyright (C) 2013  Mike Gerwitz
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.
##

sstrip()
{
  base="$( basename "$1" )"
  echo "${1%/*}/${base#??-}"
}

[ -n "$2" ] || {
  echo "Usage: $0 src dest" >&2
  exit 64
}

# ensure that parent directory exists
mkdir -p "${dest%/*}"

dest="$( sstrip "$2" )"
cp -v "$1" "$dest"
